runtime: nodejs
env: flex
env_variables:
  DATABASE_USER: $DATABASE_USER
  DATABASE_PASSWORD: $DATABASE_PASSWORD
  DATABASE_NAME: $DATABASE_NAME
  INSTANCE_CONNECTION_NAME: $INSTANCE_CONNECTION_NAME
  DATABASE_SOCKET_PATH: $DATABASE_SOCKET_PATH
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7
